INSERT INTO public.strains (id,name,type,thc_min,thc_max,cbd_min,cbd_max,description,effects,flavors,terpenes,genetics,difficulty,flowering_time,yield,rating,rating_count,source) VALUES
('mexican-landrace-acapulco-gold','Acapulco Gold','sativa',18,24,0.1,0.5,'Mexican Landrace cut. Pure Mexican Sativa producing earthy-woody-herbal nose and relaxed sleepy balanced effects.','{"Relaxed","Sleepy","Happy","Hungry"}','{"Earthy","Woody","Herbal","Spicy"}','[{"name":"Myrcene","percentage":0.52},{"name":"Humulene","percentage":0.28},{"name":"Caryophyllene","percentage":0.2}]'::jsonb,'Pure Mexican Sativa','moderate','8-9 weeks','450 g/m²',0,0,'Mexican Landrace'),
('panamanian-landrace-panama-red','Panama Red','sativa',18,24,0.1,0.5,'Panamanian Landrace cut. Pure Panamanian Sativa producing haze-pine-citrus nose and energetic uplifted balanced effects.','{"Energetic","Uplifted","Creative","Focused"}','{"Haze","Pine","Citrus","Spice"}','[{"name":"Terpinolene","percentage":0.52},{"name":"Pinene","percentage":0.28},{"name":"Limonene","percentage":0.2}]'::jsonb,'Pure Panamanian Sativa','moderate','8-9 weeks','450 g/m²',0,0,'Panamanian Landrace'),
('hawaiian-landrace-maui-wowie','Maui Wowie','sativa',18,24,0.1,0.5,'Hawaiian Landrace cut. Hawaiian Sativa producing tropical-mango-pineapple nose and happy uplifted balanced effects.','{"Happy","Uplifted","Euphoric","Relaxed"}','{"Tropical","Mango","Pineapple","Guava"}','[{"name":"Myrcene","percentage":0.48},{"name":"Limonene","percentage":0.3},{"name":"Caryophyllene","percentage":0.2}]'::jsonb,'Hawaiian Sativa','moderate','8-9 weeks','450 g/m²',0,0,'Hawaiian Landrace'),
('jamaican-landrace-lamb-s-bread','Lamb''s Bread','sativa',18,24,0.1,0.5,'Jamaican Landrace cut. Jamaican Sativa producing haze-pine-citrus nose and energetic uplifted balanced effects.','{"Energetic","Uplifted","Creative","Focused"}','{"Haze","Pine","Citrus","Spice"}','[{"name":"Terpinolene","percentage":0.52},{"name":"Pinene","percentage":0.28},{"name":"Limonene","percentage":0.2}]'::jsonb,'Jamaican Sativa','moderate','8-9 weeks','450 g/m²',0,0,'Jamaican Landrace'),
('malawi-landrace-malawi-gold','Malawi Gold','sativa',18,24,0.1,0.5,'Malawi Landrace cut. African Sativa producing haze-pine-citrus nose and energetic uplifted balanced effects.','{"Energetic","Uplifted","Creative","Focused"}','{"Haze","Pine","Citrus","Spice"}','[{"name":"Terpinolene","percentage":0.52},{"name":"Pinene","percentage":0.28},{"name":"Limonene","percentage":0.2}]'::jsonb,'African Sativa','moderate','8-9 weeks','450 g/m²',0,0,'Malawi Landrace'),
('colombian-landrace-colombian-gold','Colombian Gold','sativa',18,24,0.1,0.5,'Colombian Landrace cut. Santa Marta Sativa producing earthy-woody-herbal nose and relaxed sleepy balanced effects.','{"Relaxed","Sleepy","Happy","Hungry"}','{"Earthy","Woody","Herbal","Spicy"}','[{"name":"Myrcene","percentage":0.52},{"name":"Humulene","percentage":0.28},{"name":"Caryophyllene","percentage":0.2}]'::jsonb,'Santa Marta Sativa','moderate','8-9 weeks','450 g/m²',0,0,'Colombian Landrace'),
('thai-landrace-highland-thai','Highland Thai','sativa',18,24,0.1,0.5,'Thai Landrace cut. Thai Sativa Landrace producing haze-pine-citrus nose and energetic uplifted balanced effects.','{"Energetic","Uplifted","Creative","Focused"}','{"Haze","Pine","Citrus","Spice"}','[{"name":"Terpinolene","percentage":0.52},{"name":"Pinene","percentage":0.28},{"name":"Limonene","percentage":0.2}]'::jsonb,'Thai Sativa Landrace','moderate','8-9 weeks','450 g/m²',0,0,'Thai Landrace'),
('mexican-landrace-oaxacan-highland','Oaxacan Highland','sativa',18,24,0.1,0.5,'Mexican Landrace cut. Oaxacan Mexican Sativa producing haze-pine-citrus nose and energetic uplifted balanced effects.','{"Energetic","Uplifted","Creative","Focused"}','{"Haze","Pine","Citrus","Spice"}','[{"name":"Terpinolene","percentage":0.52},{"name":"Pinene","percentage":0.28},{"name":"Limonene","percentage":0.2}]'::jsonb,'Oaxacan Mexican Sativa','moderate','8-9 weeks','450 g/m²',0,0,'Mexican Landrace'),
('himalayan-landrace-nepalese','Nepalese','indica',19,26,0.1,0.5,'Himalayan Landrace cut. Nepali Indica producing earthy-woody-herbal nose and relaxed sleepy balanced effects.','{"Relaxed","Sleepy","Happy","Hungry"}','{"Earthy","Woody","Herbal","Spicy"}','[{"name":"Myrcene","percentage":0.52},{"name":"Humulene","percentage":0.28},{"name":"Caryophyllene","percentage":0.2}]'::jsonb,'Nepali Indica','moderate','8-9 weeks','450 g/m²',0,0,'Himalayan Landrace'),
('afghan-landrace-hindu-kush-pure','Hindu Kush Pure','indica',19,26,0.1,0.5,'Afghan Landrace cut. Hindu Kush Mountain producing earthy-woody-herbal nose and relaxed sleepy balanced effects.','{"Relaxed","Sleepy","Happy","Hungry"}','{"Earthy","Woody","Herbal","Spicy"}','[{"name":"Myrcene","percentage":0.52},{"name":"Humulene","percentage":0.28},{"name":"Caryophyllene","percentage":0.2}]'::jsonb,'Hindu Kush Mountain','moderate','8-9 weeks','450 g/m²',0,0,'Afghan Landrace'),
('lebanese-landrace-lebanese','Lebanese','indica',19,26,0.1,0.5,'Lebanese Landrace cut. Bekaa Valley Indica producing earthy-woody-herbal nose and relaxed sleepy balanced effects.','{"Relaxed","Sleepy","Happy","Hungry"}','{"Earthy","Woody","Herbal","Spicy"}','[{"name":"Myrcene","percentage":0.52},{"name":"Humulene","percentage":0.28},{"name":"Caryophyllene","percentage":0.2}]'::jsonb,'Bekaa Valley Indica','moderate','8-9 weeks','450 g/m²',0,0,'Lebanese Landrace'),
('moroccan-landrace-moroccan','Moroccan','indica',19,26,0.1,0.5,'Moroccan Landrace cut. Rif Mountain Indica producing earthy-woody-herbal nose and relaxed sleepy balanced effects.','{"Relaxed","Sleepy","Happy","Hungry"}','{"Earthy","Woody","Herbal","Spicy"}','[{"name":"Myrcene","percentage":0.52},{"name":"Humulene","percentage":0.28},{"name":"Caryophyllene","percentage":0.2}]'::jsonb,'Rif Mountain Indica','moderate','8-9 weeks','450 g/m²',0,0,'Moroccan Landrace'),
('afghan-landrace-afghan-kush-pure','Afghan Kush Pure','indica',19,26,0.1,0.5,'Afghan Landrace cut. Pure Afghan producing earthy-woody-herbal nose and relaxed sleepy balanced effects.','{"Relaxed","Sleepy","Happy","Hungry"}','{"Earthy","Woody","Herbal","Spicy"}','[{"name":"Myrcene","percentage":0.52},{"name":"Humulene","percentage":0.28},{"name":"Caryophyllene","percentage":0.2}]'::jsonb,'Pure Afghan','moderate','8-9 weeks','450 g/m²',0,0,'Afghan Landrace'),
('south-african-swazi-gold','Swazi Gold','sativa',18,24,0.1,0.5,'South African cut. Swaziland Sativa producing earthy-woody-herbal nose and relaxed sleepy balanced effects.','{"Relaxed","Sleepy","Happy","Hungry"}','{"Earthy","Woody","Herbal","Spicy"}','[{"name":"Myrcene","percentage":0.52},{"name":"Humulene","percentage":0.28},{"name":"Caryophyllene","percentage":0.2}]'::jsonb,'Swaziland Sativa','moderate','8-9 weeks','450 g/m²',0,0,'South African'),
('dna-chocolope','Chocolope','sativa',18,24,0.1,0.5,'DNA cut. OG Chocolate Thai x Cannalope Haze producing earthy-woody-herbal nose and relaxed sleepy balanced effects.','{"Relaxed","Sleepy","Happy","Hungry"}','{"Earthy","Woody","Herbal","Spicy"}','[{"name":"Myrcene","percentage":0.52},{"name":"Humulene","percentage":0.28},{"name":"Caryophyllene","percentage":0.2}]'::jsonb,'OG Chocolate Thai x Cannalope Haze','moderate','8-9 weeks','450 g/m²',0,0,'DNA')
ON CONFLICT (id) DO NOTHING;